version: "3.9"

services:

  neo4j:
    image: neo4j
    volumes:
      - ./data:/data
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/gradvek
      NEO4J_dbms_security_auth__minimum__password__length: 7

  gradvek:
    image: sheelyn/ns_gradvek_test
    ports:
      - "3000:3000"
      - "8080:8080"